# Generated by Django 3.0.7 on 2020-12-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201224_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='categories',
        ),
    ]
