# Generated by Django 3.0.7 on 2020-12-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201224_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.IntegerField(default=0, help_text='level of importance')),
                ('url', models.URLField()),
                ('date_posted', models.DateField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('sub_categories', models.ManyToManyField(to='projects.SubCategory')),
            ],
            options={
                'ordering': ['weight', '-date_posted'],
            },
        ),
    ]
