# Generated by Django 3.0.7 on 2020-12-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['weight', '-time_last_edited']},
        ),
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=0, help_text='level of importance'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, help_text='url to public work', null=True),
        ),
    ]
