# Generated by Django 3.0.7 on 2020-12-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201224_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
